version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REPO_URI
      - echo "CodeBuild Build Number:${CODEBUILD_BUILD_NUMBER}"
      - echo "ECR Repository URI:${ECR_REPO_URI}"
      - echo "Image Tag:${CODEBUILD_BUILD_NUMBER}"

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t ${ECR_REPO_URI}:${CODEBUILD_BUILD_NUMBER} .
      - docker tag ${ECR_REPO_URI}:${CODEBUILD_BUILD_NUMBER} ${ECR_REPO_URI}:latest

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images to ECR...
      - docker push ${ECR_REPO_URI}:${CODEBUILD_BUILD_NUMBER}
      - docker push ${ECR_REPO_URI}:latest

artifacts:
  files:
    - "**/*"
  discard-paths: yes
